## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: IfNotPresent
image: cloudstudio-devops-docker.pkg.coding.net/artifacts/routerlicious/redis:alpine